server:
  port: 8080
  servlet:
    context-path: /api/v1/
spring:
  servlet:
    multipart:
      max-file-size: 5MB
  application:
    name: blogball
  datasource:
    url: jdbc:postgresql://localhost:5432/blogball
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  default-produces-media-type: application/json



